### ISSUE TITLE
map.fitBounds with maxZoom=undefined throws `Invalid LngLat object: (NaN, NaN)`

### ISSUE THREAD

**Issue by theprojectsomething** [mapbox/mapbox-gl-js#10013]
**mapbox-gl-js version**: 1.12.0

**browser**: All of them

### Steps to Trigger Behavior

 1. Create a map
 2. fit it to some bounds
 3. this time, stuff up and pass it an undefined value for `maxZoom` without realising
 4. spend many hours debugging 

### Link to Demonstration

https://jsfiddle.net/jxoya0cn/

### Expected Behavior
Warn that an invalid value has been passed. Disregard / allow for an invalid zoom constraint.

### Actual Behavior
💣 `Invalid LngLat object: (NaN, NaN)`

**Comment by jaybo** [comment]
Possibly the same bug, but different trigger situation.  To the best of my knowledge, I didn't set `maxZoom` to undefined value.
Stack:
```
onViewReset Error: Invalid LngLat object: (NaN, NaN)
    at new bc (webpack-internal:///./node_modules/mapbox-gl/dist/mapbox-gl.js:30:310627)
    at zc.toLngLat (webpack-internal:///./node_modules/mapbox-gl/dist/mapbox-gl.js:30:312227)
    at io.coordinateLocation (webpack-internal:///./node_modules/mapbox-gl/dist/mapbox-gl.js:34:279296)
    at eval (webpack-internal:///./node_modules/mapbox-gl/dist/mapbox-gl.js:34:282144)
    at Array.reduce (<anonymous>)
    at io._getBounds3D (webpack-internal:///./node_modules/mapbox-gl/dist/mapbox-gl.js:34:282116)
    at io.getBounds (webpack-internal:///./node_modules/mapbox-gl/dist/mapbox-gl.js:34:281450)
    at Map.getBounds (webpack-internal:///./node_modules/mapbox-gl/dist/mapbox-gl.js:34:361667)
    at onViewReset (webpack-internal:///./src/modules/tideEngine.js:970:20)
    at eval (webpack-internal:///./src/modules/tideEngine.js:533:9) {stack: 'Error: Invalid LngLat object: (NaN, NaN)
```

**Comment by jonesmac** [comment]
Similar experience.  I don't think the issue is on the initial map load. but when an additional `maxZoom` value is passed AFTER the map has been configured.

**Comment by SnailBones** [comment]
From https://github.com/mapbox/mapbox-gl-js/pull/12098#issuecomment-1192846934:

> While this is a useful exception on developer errors, we don't have precedent of type safety errors on other APIs. Type safety is done with static type annotations, and while I imagine that not all external developer adopt the same type checking as part of their tooling, it's not trivial to exhaust every possible type checks at runtime as this is better suited for static analysis. If we introduce this, we would start to be inconsistent with other APIs and probably be asked to adopt similar patterns elsewhere.
