### ISSUE TITLE
mapboxgl.Marker: Check if parentNode exists before trying to removechild

### ISSUE THREAD

**Issue by Liquan-gdut** [mapbox/mapbox-gl-js#10130]
Fixes bug relating to marker removal if marker has already been removed.

Markers include an option to closeOnClick. If the user manually removes the marker by some other method (a timeout, clicking a clear button etc,), and then clicks the map, the console logs an error because the marker has already been removed:
```
Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at removeChild (http://localhost:6006/vendors~main.a2c8599a6d68fdbec004.bundle.js:178368:18)
    at unmountHostComponents (http://localhost:6006/vendors~main.a2c8599a6d68fdbec004.bundle.js:191216:9)
    at commitDeletion (http://localhost:6006/vendors~main.a2c8599a6d68fdbec004.bundle.js:191267:5)
    at commitMutationEffects (http://localhost:6006/vendors~main.a2c8599a6d68fdbec004.bundle.js:193549:11)
    at HTMLUnknownElement.callCallback (http://localhost:6006/vendors~main.a2c8599a6d68fdbec004.bundle.js:170955:14)
    at Object.invokeGuardedCallbackDev (http://localhost:6006/vendors~main.a2c8599a6d68fdbec004.bundle.js:171004:16)
    at invokeGuardedCallback (http://localhost:6006/vendors~main.a2c8599a6d68fdbec004.bundle.js:171059:31)
    at commitRootImpl (http://localhost:6006/vendors~main.a2c8599a6d68fdbec004.bundle.js:193276:9)
    at unstable_runWithPriority (http://localhost:6006/vendors~main.a2c8599a6d68fdbec004.bundle.js:199692:12)
    at runWithPriority$1 (http://localhost:6006/vendors~main.a2c8599a6d68fdbec004.bundle.js:181806:10)
```

**it is similar to [#5059](https://github.com/mapbox/mapbox-gl-js/pull/5059),  [#2395](https://github.com/mapbox/mapbox-gl-js/pull/2395)**

**mapbox-gl-js version**:1.13.0

**browser**:chrome

**Comment by aparshin** [comment]
@Liquan-gdut Are you talking about Markers or about Popups (`closeOnClick` is an option of Popup)? I failed to reproduce this issue with v1.13.0. Do you have an online example with this issue (JSFiddle or similar)?

**Comment by karimnaaji** [comment]
I haven't been able to reproduce either after a some testing so I'll go ahead and close. Feel free to reopen this ticket with a working example if this is still an issue for you!
