### ISSUE TITLE
render tests error locally with "Error: style.json is missing"

### ISSUE THREAD

**Issue by ansis** [mapbox/mapbox-gl-js#10469]
**mapbox-gl-js version**: main

### Steps to Trigger Behavior

 1. yarn run test-render

### Expected Behavior

Passes (like it does on CI).

### Actual Behavior

```
ok 1359 Chrome 89.0 - [undefined ms] - render-tests/zoom-visibility/was-above
ok 1360 Chrome 89.0 - [undefined ms] - render-tests/zoom-visibility/was-below
ok 1361 Chrome 89.0 - [undefined ms] - render-tests/zoomed-fill/default
ok 1362 Chrome 89.0 - [undefined ms] - render-tests/zoomed-fill/negative-zoom
ok 1363 Chrome 89.0 - [undefined ms] - render-tests/zoomed-raster/fractional
ok 1364 Chrome 89.0 - [undefined ms] - render-tests/zoomed-raster/overzoom
ok 1365 Chrome 89.0 - [undefined ms] - render-tests/zoomed-raster/underzoom
not ok 1366 Chrome 89.0 - [undefined ms] - Error: style.json is missing
    ---
        ok: >
            false
        id: >
            1366
        name: >
            Error: style.json is missing
        diag: >
            [object Object]
        stack: >
            |-
              Error: style.json is missing
                  at Test.runTest (http://localhost:7357/test/integration/dist/integration-test.js:141967:19)
                  at Test.bound [as _cb] (http://localhost:7357/test/integration/dist/tape.js:10358:32)
                  at Test.run (http://localhost:7357/test/integration/dist/tape.js:10375:31)
                  at Test.bound [as run] (http://localhost:7357/test/integration/dist/tape.js:10358:32)
                  at Test._end (http://localhost:7357/test/integration/dist/tape.js:10469:11)
                  at Test.bound [as _end] (http://localhost:7357/test/integration/dist/tape.js:10358:32)
                  at Test.end (http://localhost:7357/test/integration/dist/tape.js:10458:10)
                  at Test.bound [as end] (http://localhost:7357/test/integration/dist/tape.js:10358:32)
                  at Test.ensureTeardown (http://localhost:7357/test/integration/dist/integration-test.js:141955:7)
                  at Test.bound [as _cb] (http://localhost:7357/test/integration/dist/tape.js:10358:32)
            
        operator: >
            error
        browser log: |
    ...

1..1366
# tests 1366
# pass  1364
# skip  0
# todo  0
# fail  2
```

It's a bit odd because there is no assertion # `1366` when running on CI.

**Comment by arindam1993** [comment]
I think this happened because you have a folder on disk with gitignored `expected.png` in it that isnt committed to git.

**Comment by ansis** [comment]
Yep! thanks
