### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by haoziluo** [mapbox/mapbox-gl-js#1061]
```
npm WARN package.json feature-filter@1.0.0 No repository field.
npm WARN package.json glify@0.4.2 No repository field.
npm WARN package.json mapbox-gl-test-suite@0.0.0 No repository field.
npm WARN package.json pngjs@0.4.0 No repository field.

> gl@0.0.4 install /home/luohao/mapbox-gl-js/node_modules/gl
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/home/luohao/.node-gyp/0.10.36"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/home/luohao/mapbox-gl-js/node_modules/gl/.node-gyp"
Usage: gyp_main.py [options ...] [build_file ...]

gyp_main.py: error: no such option: --no-parallel
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 3.13.0-44-generic
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/luohao/mapbox-gl-js/node_modules/gl
gyp ERR! node -v v0.10.36
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok 
npm WARN optional dep failed, continuing gl@0.0.4
npm WARN cannot run in wd mapbox-gl@0.7.0 npm run build && npm run production (wd=/home/luohao/mapbox-gl-js)
```

my os is ubuntu 14.04 64bits, node version is 0.10.36

**Comment by jfirebaugh** [comment]
> gyp WARN EACCES user "root" does not have permission to access the dev dir "/home/luohao/.node-gyp/0.10.36"

This looks like a permissions error. Can you try to sort that out?

**Comment by haoziluo** [comment]
but I use "sudo"....

**Comment by misterfresh** [comment]
on Windows if you want to "npm install mapbox-gl" you will first need to follow these instructions https://github.com/TooTallNate/node-gyp/wiki/Visual-Studio-2010-Setup

**Comment by tmcw** [comment]
@haoziluo any luck fixing permissions on your user & npm directory?

**Comment by tmcw** [comment]
Closing: more information is needed to debug this issue.
