### ISSUE TITLE
Uncaught RangeError: out of range source coordinates for DEM data, new in 2.4.0

### ISSUE THREAD

**Issue by jaybo** [mapbox/mapbox-gl-js#10927]
**mapbox-gl-js version**:  2.4.0

**browser**: Chrome 92.0.4515.131, also happens on Edge.

### Steps to Trigger Behavior

 1. Switch from 2D to 3D map view.
 2. Attempt to edit an existing route using Mapbox Draw.
 3. A stream of "Uncaught RangeError: out of range source coordinates for DEM data" are thrown preventing editing the route, and sometimes even moving the map.

### Link to Demonstration

1. Got to www.deepzoom.com (use desktop, not mobile device)
2. Select the "Kayak Cordova" demo.
3. Let the demo run for a moment, then click the stop animation button.  Click the "Exit Demos" button.
4. Go to the "Route" tab. Click the "Edit" button.  A stream of the following errors will appear:
```
Uncaught RangeError: out of range source coordinates for DEM data
    at dh._idx (vendor.5a8c0eaf.js:19)
    at dh.get (vendor.5a8c0eaf.js:19)
    at wh.getElevationAt (vendor.5a8c0eaf.js:19)
    at circle.queryIntersectsFeature (vendor.5a8c0eaf.js:19)
    at vendor.5a8c0eaf.js:19
    at Ah.loadMatchingFeature (vendor.5a8c0eaf.js:19)
    at Ah.query (vendor.5a8c0eaf.js:19)
    at eh.queryRenderedFeatures (vendor.5a8c0eaf.js:19)
    at ke (vendor.5a8c0eaf.js:19)
    at jt.queryRenderedFeatures (vendor.5a8c0eaf.js:19)
    
```

    5. This problem did NOT exist in mapbox gl V2.3.1 or earlier versions.
    6. The issue is perhaps related to the steep terrain in this area?  It doesn't seem to trigger as easily in other locations.

### Actual Behavior
![Capture](https://user-images.githubusercontent.com/1607323/129160286-59cd4fe3-c36b-4943-9e42-64937bd62a36.PNG)

**Comment by jaybo** [comment]
Perhaps another clue:  previously, this same demo script would trigger #10610

**Comment by jaybo** [comment]
More information:  
1. This error **only** happens when 3D is enabled.
2. This error **only** happens when a route is either being drawn or displayed using Mapbox Draw.
3. The problem can happen at any latitude, any zoom, and any topography (including routes strictly defined at sea level).

**Comment by jaybo** [comment]
Here's a more complete stack trace:
![image](https://user-images.githubusercontent.com/1607323/129949954-921b64b6-5928-4f57-ae46-adfc77c07dd4.png)

**Comment by jaybo** [comment]
Y seems to be out of range:
![image](https://user-images.githubusercontent.com/1607323/129963324-364b9e4c-503d-4af8-bda7-4023ed557bd2.png)

**Comment by jaybo** [comment]
OK, it's related to the style of circle midpoints.  
If I remove the "gl-draw-polygon-and-line-vertex-static" midpoint style from this pen, the problem goes away:
https://codepen.io/jaybonomad/pen/vYmqrRP
(I usually need to draw about 10 line segments to make the exception happen)

**Comment by jaybo** [comment]
Possibly related? https://github.com/mapbox/mapbox-gl-draw/issues/1063

**Comment by SnailBones** [comment]
Thanks for your thorough work looking into this @jaybo! I can confirm that this is still occurring despite the resolution of #10610.

**Comment by jaybo** [comment]
Just a friendly reminder that this is still an issue with 2.7.0.  Here's a codepen:
https://codepen.io/jaybonomad/pen/gOXrKqL

Move to Cordova and draw a polyline with the map at a 45 degree rotation.

**Comment by jaybo** [comment]
I'm guessing the origin of the bug is: https://github.com/mapbox/mapbox-gl-draw/issues/1077

**Comment by jaybo** [comment]
Just a friendly reminder that this is still an issue with mapbox-gl 2.10.0. Here's a codepen:
https://codepen.io/jaybonomad/pen/gOXrKqL

Draw a polyline with the map at a 45 degree pitch. Zoom in and out and rotate the map for maybe a minute. Eventually, out comes a steady stream of:
```
dem_data.js:102 
        
       Uncaught RangeError: out of range source coordinates for DEM data
    at Ld._idx (dem_data.js:102:80)
    at Ld.get (dem_data.js:88:28)
    at Yd.getElevationAt (elevation.js:288:29)
    at ru (circle_style_layer.js:104:70)
    at circle.queryIntersectsFeature (circle_style_layer.js:66:16)
    at feature_index.js:164:39
    at Wd.loadMatchingFeature (feature_index.js:225:56)
    at Wd.query (feature_index.js:150:18)
    at Id.queryRenderedFeatures (tile.js:440:40)
    at Re (query_features.js:47:43)
```

**Comment by jaybo** [comment]
Just a friendly reminder that this is still an issue with mapbox-gl 2.12 and mapbox-gl-draw 1.3.0.  Here's a codepen:
https://codepen.io/jaybonomad/pen/gOXrKqL

Draw a polyline with the map at a 45 degree pitch.  Finish the polyline and then click anywhere except the polyline.
```
Uncaught RangeError: out of range source coordinates for DEM data
    at Zd._idx (dem_data.js:102:80)
    at Zd.get (dem_data.js:88:28)
    at ay.getElevationAt (elevation.js:315:29)
    at ou (circle_style_layer.js:105:70)
    at circle.queryIntersectsFeature (circle_style_layer.js:67:16)
    at feature_index.js:165:39
    at oy.loadMatchingFeature (feature_index.js:226:56)
    at oy.query (feature_index.js:151:18)
    at Ld.queryRenderedFeatures (tile.js:438:40)
    at Re (query_features.js:47:43)
```

**Comment by stepankuzmin** [comment]
Hi @jaybo,

I'm sorry for not getting back to you sooner. I can confirm the issue, and unfortunately, it's still present with the [filter modes bugfix](https://github.com/mapbox/mapbox-gl-draw/pull/1078) applied in GL Draw.

**Comment by Quietly-20201113** [comment]
mapbox-gl 3.7.0 mapbox-gl-draw 1.4.3 Not yet resolved

**Comment by timbtimbtimb** [comment]
This is still not resolved I'm afraid
