### ISSUE TITLE
`collect-stats` job is failing

### ISSUE THREAD

**Issue by mourner** [mapbox/mapbox-gl-js#11285]
The `collect-stats` job is failing since https://github.com/mapbox/mapbox-gl-js/commit/9f85967d7ba67fb257ab679657a05b4a192f97d8, although the changes there seem unrelated. Let's investigate this so that we can have green builds in `main` again.

[Example fail](https://app.circleci.com/pipelines/github/mapbox/mapbox-gl-js/8592/workflows/926177ad-be17-4a3b-ac65-e88e0c59f9c6/jobs/110553):

```
collecting stats...
(node:356) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token . in JSON at position 1
    at JSON.parse (<anonymous>)
    at file:///home/circleci/mapbox-gl-js/bench/gl-stats.js:35:24
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by stepankuzmin** [comment]
The verbose logging causes the problem ([dumpio](https://app.circleci.com/pipelines/github/mapbox/mapbox-gl-js/8597/workflows/bb0de71c-87a4-4b7b-bc3a-4b55e316e02a/jobs/110622?invite=true#step-103-10))

```
[1116/140420.301852:ERROR:gl_utils.cc(318)] [.WebGL-0x2c1a000f9500]GL Driver Message (OpenGL, Performance, GL_CLOSE_PATH_NV, High): GPU stall due to ReadPixels
[1116/140420.334670:INFO:CONSOLE(0)] "[.WebGL-0x2c1a000f9500]GL Driver Message (OpenGL, Performance, GL_CLOSE_PATH_NV, High): GPU stall due to ReadPixels", source: about:blank (0)
```

We can skip console messages until we see the first log message, but I'm not sure if these logs are important or not.
