### ISSUE TITLE
map.preloadOnly does not work (exception fired)

### ISSUE THREAD

**Issue by fvisticot** [mapbox/mapbox-gl-js#12696]
**mapbox-gl-js version**: 2.14.1

**browser**: chrome

### Steps to Trigger Behavior

`map.flyTo({
            ...end,
            duration: 6500,
            essential: true,
            preloadOnly: true
        })`

### Actual Behavior

`urce_cache.js:1025 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'tileZoom')
    at source_cache.js:1025:108
    at util.js:277:9
    at Array.forEach (<anonymous>)
    at M (util.js:276:11)
    at sy._preloadTiles (source_cache.js:1024:9)
    at map.js:3596:52
    at util.js:277:9
    at Array.forEach (<anonymous>)
    at Object.M [as asyncAll] (util.js:276:11)
    at Map._preloadTiles (map.js:3596:9)
(`

**Comment by mourner** [comment]
Can you please provide a minimal live example reproducing the error, as prompted in the issue template?

**Comment by fvisticot** [comment]
> Can you please provide a minimal live example reproducing the error, as prompted in the issue template?

issue details updated

**Comment by stepankuzmin** [comment]
I can confirm this issue. It appears when you try preloading tiles right after adding a source until it's loaded. Here is the fix https://github.com/mapbox/mapbox-gl-js/pull/12699
