### ISSUE TITLE
3.0.0-beta.1: Map.setLayoutProperty fails for custom layers

### ISSUE THREAD

**Issue by fbellomi** [mapbox/mapbox-gl-js#12858]
I switched to 3.0.0-beta.1 and Map.setLayoutProperty consistently fails for custom layers, with the following stack trace

```
TypeError: Cannot read properties of undefined (reading 'setValue')
    at mb.setLayoutProperty (style_layer.js:146:33)
    at aA.setLayoutProperty (style.js:1676:15)
    at Map.setLayoutProperty (map.js:2784:20)
```

**mapbox-gl-js version**: 3.0.0-beta.1

**browser**: chrome 116 macOs

### Steps to Trigger Behavior

In [this fiddle](https://jsfiddle.net/xtr64z8f/) I modified the example in 
https://docs.mapbox.com/mapbox-gl-js/example/custom-style-layer/
changing the version of the lib and adding a call to setLayoutProperty

### Link to Demonstration

https://jsfiddle.net/xtr64z8f/

**Comment by kumiko-haraguchi** [comment]
@stepankuzmin If no one is working on this issue yet, can I take it? I've made a [draft PR](https://github.com/mapbox/mapbox-gl-js/pull/12872). If it's not necessary, I'll close it!

**Comment by stepankuzmin** [comment]
Hi @fbellomi,

The fix for this issue will be available in the upcoming beta release.

@kumiko-haraguchi, thanks a lot for the contribution, but as this is already fixed, I will close your PR. Sorry for not indicating that this is already fixed in the issue 🙏

**Comment by fbellomi** [comment]
I tested with beta2 and it appears the issue is resolved
