### ISSUE TITLE
Spin/Rotate Globe issue while accessing from US region 

### ISSUE THREAD

**Issue by maulikpatel-prescinto** [mapbox/mapbox-gl-js#12933]
**mapbox-gl-js version**: v2.14.1

**browser**: Chrome

### Steps to Trigger Behavior

 1. Login from US region
 2. Open a demo link - https://docs.mapbox.com/mapbox-gl-js/example/globe-spin/
 3. Globe rotation does not work and throws an error as below

main.420db4fcdb540c4c.js?v=0.2.256:1 **ERROR RangeError: Maximum call stack size exceeded**
    at a.error (main.420db4fcdb540c4c.js?v=0.2.256:1:2963955)
    at a._next (main.420db4fcdb540c4c.js?v=0.2.256:1:2974009)
    at a.next (main.420db4fcdb540c4c.js?v=0.2.256:1:2963849)
    at Map.v (main.420db4fcdb540c4c.js?v=0.2.256:1:2971508)
    at Map.fire (529.ccb7f80bb285b994.js:1:2671161)
    at Map._fireMoveEvents (529.ccb7f80bb285b994.js:1:3556675)
    at 529.ccb7f80bb285b994.js:1:3555884
    at Map._ease (529.ccb7f80bb285b994.js:1:3559987)
    at Map.easeTo (529.ccb7f80bb285b994.js:1:3556243)
    at W.**spinGlobe** (main.420db4fcdb540c4c.js?v=0.2.256:1:663701)

**Comment by stepankuzmin** [comment]
Hi @maulikpatel-prescinto,

Please include information about the browser version and operating system used. Also, could you let me know if there are any logs or errors in the Browser console?
