### ISSUE TITLE
unreliable camera tests

### ISSUE THREAD

**Issue by ansis** [mapbox/mapbox-gl-js#2332]
**mapbox-gl-js version**: master

### Steps to Trigger Behavior

 1. `npm test`

### Expected Behavior

All tests pass.

### Actual Behavior

Occasionally two tests fail:

https://circleci.com/gh/mapbox/mapbox-gl-js/2765

```
1006 passing (46s)
  2 failing

  1) test/js/ui/camera.test.js camera #flyTo pans eastward across the prime meridian expect truthy value:
     Error: expect truthy value
      at null.<anonymous> (test/js/ui/camera.test.js:879:19)
      at Evented.fire (js/util/evented.js:9:2919)
      at null.<anonymous> (js/ui/camera.js:9:20420)
      at util.extend._finishEase (js/ui/camera.js:9:22157)
      at null.<anonymous> (js/ui/camera.js:9:21655)
      at tick [as _onTimeout] (js/util/browser.js:9:1296)

  2) test/js/ui/camera.test.js camera #flyTo pans westward across the prime meridian expect truthy value:
     Error: expect truthy value
      at null.<anonymous> (test/js/ui/camera.test.js:898:19)
      at Evented.fire (js/util/evented.js:9:2919)
      at null.<anonymous> (js/ui/camera.js:9:20420)
      at util.extend._finishEase (js/ui/camera.js:9:22157)
      at null.<anonymous> (js/ui/camera.js:9:21655)
      at tick [as _onTimeout] (js/util/browser.js:9:1296)
```

**Comment by lucaswoj** [comment]
This has been fixed now!
