### ISSUE TITLE
mapbox-gl-shaders - 404 error on npm install

### ISSUE THREAD

**Issue by benjamindulau** [mapbox/mapbox-gl-js#2754]
Hi,

I'm getting a 404 error when trying to install mapbox-gl with npm.

```bash
$ npm install --save-dev mapbox-gl
```

```bash
npm http 404 https://registry.npmjs.org/mapbox-gl-shaders
npm ERR! TypeError: Object.keys called on non-object
npm ERR!     at Function.keys (native)
npm ERR!     at installTargetsError (/usr/lib/node_modules/npm/lib/cache.js:708:24)
npm ERR!     at /usr/lib/node_modules/npm/lib/cache.js:638:10
npm ERR!     at saved (/usr/lib/node_modules/npm-registry-client/lib/get.js:148:7)
npm ERR!     at /usr/lib/node_modules/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:108:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>
```

Maybe this is a momentarily error..

Thanks.

**Comment by lucaswoj** [comment]
I just did a fresh install using the command you specify and was unable to reproduce the error

```bash
$ npm install --save-dev mapbox-gl
npm WARN deprecated mapbox-gl-js-supported@1.1.0: This project has been renamed to mapbox-gl-supported. Install using mapbox-gl-supported instead.
npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN peerDependencies The peer dependency browserify@>= 5 included from minifyify will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
mapbox-gl@0.20.0 node_modules/mapbox-gl
├── csscolorparser@1.0.2
├── quickselect@1.0.0
├── unitbezier@0.0.0
├── mapbox-gl-js-supported@1.1.0
├── grid-index@0.1.0
├── mapbox-gl-function@1.2.1
├── resolve-url@0.2.1
├── webworkify@1.2.0
├── feature-filter@2.1.0
├── earcut@2.1.1
├── point-geometry@0.0.0
├── vt-pbf@2.0.2
├── vector-tile@1.2.1
├── shelf-pack@1.0.0
├── whoots-js@2.0.0
├── gl-matrix@2.3.2
├── geojson-vt@2.1.8
├── pngjs@2.3.1
├── geojson-rewind@0.1.0 (minimist@0.0.5, geojson-area@0.1.0, concat-stream@1.2.1)
├── pbf@1.3.7 (ieee754@1.1.6, resolve-protobuf-schema@2.0.0)
├── envify@3.4.0 (through@2.3.8, jstransform@10.1.0)
├── request@2.72.0 (tunnel-agent@0.4.3, aws-sign2@0.6.0, forever-agent@0.6.1, oauth-sign@0.8.2, is-typedarray@1.0.0, caseless@0.11.0, stringstream@0.0.5, aws4@1.4.1, isstream@0.1.2, json-stringify-safe@5.0.1, extend@3.0.0, tough-cookie@2.2.2, node-uuid@1.4.7, qs@6.1.0, combined-stream@1.0.5, mime-types@2.1.11, form-data@1.0.0-rc4, bl@1.1.2, hawk@3.1.3, http-signature@1.1.1, har-validator@2.0.6)
├── supercluster@2.1.0 (kdbush@1.0.0)
├── mapbox-gl-shaders@1.0.0 (brfs@1.4.3)
├── mapbox-gl-style-spec@8.7.0 (minimist@0.0.8, sort-object@0.3.2, rw@0.1.4, lodash.isequal@3.0.4, glob@4.0.6, jsonlint-lines-primitives@1.6.0)
├── unassertify@2.0.3 (esprima@2.7.2, through@2.3.8, convert-source-map@1.2.0, escodegen@1.8.0, multi-stage-sourcemap@0.2.1, unassert@1.4.0)
├── browserify@13.0.1 (browser-resolve@1.11.2, https-browserify@0.0.1, tty-browserify@0.0.0, path-browserify@0.0.0, duplexer2@0.1.4, punycode@1.4.1, string_decoder@0.10.31, constants-browserify@1.0.0, os-browserify@0.1.2, inherits@2.0.1, process@0.11.5, htmlescape@1.1.1, stream-browserify@2.0.1, assert@1.3.0, defined@1.0.0, domain-browser@1.1.7, xtend@4.0.1, read-only-stream@2.0.0, querystring-es3@0.2.1, timers-browserify@1.4.2, util@0.10.3, deps-sort@2.0.0, parents@1.0.1, events@1.1.0, vm-browserify@0.0.4, has@1.0.1, console-browserify@1.1.0, shell-quote@1.6.0, url@0.11.0, readable-stream@2.1.4, subarg@1.0.0, labeled-stream-splicer@2.0.0, shasum@1.0.2, glob@5.0.15, concat-stream@1.5.1, stream-http@2.3.0, through2@2.0.1, JSONStream@1.1.2, buffer@4.6.0, browserify-zlib@0.1.4, syntax-error@1.1.6, resolve@1.1.7, browser-pack@6.0.1, insert-module-globals@7.0.1, crypto-browserify@3.11.0, module-deps@4.0.7)
└── minifyify@7.3.3 (through@2.3.8, convert-source-map@1.2.0, lodash.assign@4.0.9, lodash.bind@4.1.4, source-map@0.5.6, lodash.defaults@4.0.1, tmp@0.0.28, mkdirp@0.5.1, concat-stream@1.5.1, lodash.foreach@4.3.0, transform-filter@0.1.1, uglify-js@2.6.2)
```

**Comment by lucaswoj** [comment]
If the problem persists, please re-open this issue and provide some more platform information.

**Comment by jakecweston** [comment]
This appears to be happening again.  Am I missing something? https://registry.npmjs.org/mapbox-gl-shaders is currently a 404.

**Comment by Suraj59** [comment]
lucaswoj this not working any one have sol --
npm install --save-dev mapbox-gl
npm WARN deprecated geojson-area@0.1.0: This module is now under the @mapbox namespace: install @mapbox/geojson-area instead
npm ERR! path /home/esense-9/.npm/_cacache/index-v5/be/66
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall mkdir
npm ERR! Error: EACCES: permission denied, mkdir '/home/esense-9/.npm/_cacache/index-v5/be/66'
npm ERR!  { Error: EACCES: permission denied, mkdir '/home/esense-9/.npm/_cacache/index-v5/be/66'
npm ERR!   cause: 
npm ERR!    { Error: EACCES: permission denied, mkdir '/home/esense-9/.npm/_cacache/index-v5/be/66'
npm ERR!      errno: -13,
npm ERR!      code: 'EACCES',
npm ERR!      syscall: 'mkdir',
npm ERR!      path: '/home/esense-9/.npm/_cacache/index-v5/be/66' },
npm ERR!   isOperational: true,
npm ERR!   stack: 'Error: EACCES: permission denied, mkdir \'/home/esense-9/.npm/_cacache/index-v5/be/66\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: '/home/esense-9/.npm/_cacache/index-v5/be/66',
npm ERR!   parent: 'escodegen' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/esense-9/.npm/_logs/2017-10-18T06_42_24_923Z-debug.log

**Comment by sumitramteke** [comment]
There is an article as solution for *EACCESS* issues [How to Prevent Permissions Errors](https://docs.npmjs.com/getting-started/fixing-npm-permissions)
