### ISSUE TITLE
mapbox-gl-shaders - 404 error on npm install

### ISSUE THREAD

**Issue by jakecweston** [mapbox/mapbox-gl-js#2841]
Hi,

Am I missing something?  https://registry.npmjs.org/mapbox-gl-shaders is currently 404

```
$ npm install --save-dev mapbox-gl
```

```
...
npm http 404 https://registry.npmjs.org/mapbox-gl-shaders
npm ERR! TypeError: Object.keys called on non-object
npm ERR!     at Function.keys (native)
npm ERR!     at installTargetsError (/usr/lib/node_modules/npm/lib/cache.js:708:24)
npm ERR!     at /usr/lib/node_modules/npm/lib/cache.js:638:10
npm ERR!     at saved (/usr/lib/node_modules/npm-registry-client/lib/get.js:148:7)
npm ERR!     at /usr/lib/node_modules/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:108:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 4.0.6-300.fc22.x86_64
npm ERR! command "node" "/bin/npm" "install" "--save-dev" "mapbox-gl"
npm ERR! cwd /working/mapbox/mapbox-gl-native
npm ERR! node -v v0.10.42
npm ERR! npm -v 1.3.6
npm ERR! type called_on_non_object

```

Thanks

**Comment by jfirebaugh** [comment]
Node 4 or later is required, as documented [here](https://github.com/mapbox/mapbox-gl-js/blob/master/CONTRIBUTING.md#preparing-your-development-environment).
