### ISSUE TITLE
Cannot find module 'sinon'

### ISSUE THREAD

**Issue by DannyDelott** [mapbox/mapbox-gl-js#3230]
As of 0.24.0, `sinon` appears to be used outside of the testing environment:

https://github.com/mapbox/mapbox-gl-js/blob/07feb8d6e1f7be693bdeadf3d6c0300202122c0b/js/util/window.js#L5

This causes an issue with `npm install mapbox-gl`, because devDependencies are not installed with this command without explicitly using the `--dev` flag.

With webpack, this results in the following stack trace:

```js
Error: Cannot find module 'sinon'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/code/node_modules/mapbox-gl/js/util/window.js:5:13)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/code/node_modules/mapbox-gl/js/util/browser.js:8:14)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/code/node_modules/mapbox-gl/js/mapbox-gl.js:3:15)
```

**Comment by tmcw** [comment]
Two issues layered here:

* That file is in the browser field https://github.com/mapbox/mapbox-gl-js/blob/07feb8d6e1f7be693bdeadf3d6c0300202122c0b/package.json#L89 so shouldn't be included in builds. Webpack at least [claims to support that field](https://github.com/webpack/webpack/issues/151), so it should not be visited here.


> because devDependencies are not installed with this command without explicitly using the --dev flag.

This isn't technically true. By default, `npm` does install devDependencies: it's likely that you have `NODE_ENV=production` set globally, which is relatively uncommon.

Are you using something similar to the [suggested webpack configuration](https://github.com/mapbox/mapbox-gl-js#using-mapbox-gl-js-with-webpack)?

**Comment by DannyDelott** [comment]
Thanks, we are using the suggested webpack config (it's great!) and haven't configured a production env yet, so that hasn't happened yet.

Are you sure about devDependencies? According to [this answer on SO](http://stackoverflow.com/a/22004559/2193290):

> `npm install "$package"`
> In that case, you normally don't want the development dependencies, so you just get what is needed to use the package: dependencies.
> 
> If you really want to install development packages in that case, you can set the dev config option to true, possibly from the command line as:
> 
> `npm install "$package" --dev`
> The option is false by default since this is a much less common case.
>

**Comment by mourner** [comment]
@tmcw `npm install` in a mapbox-gl dir installs dev deps of mapbox-gl, but `npm install mapbox-gl` in a different dir does not.

@DannyDelott would [this solution](https://github.com/mapbox/mapbox-gl-js/issues/3229#issuecomment-248388599) be acceptable to you?

**Comment by DannyDelott** [comment]
@mourner I need `sinon` in my project anyway, so this is a motivation to refactor some home-rolled spies instead of needing a workaround.

Just wanted to document it here in case others aren't using `sinon` and have trouble with the new release.
