### ISSUE TITLE
Removing a symbol layer and immediately readding it as a circle layer causes TypeError in draw_circle

### ISSUE THREAD

**Issue by anandthakker** [mapbox/mapbox-gl-js#3633]
**mapbox-gl-js version**: 0.27

### Steps to Trigger Behavior

 1. Create a map with a symbol layer with id 'a'
 2. `map.removeLayer('a'); map.addLayer({ id: 'a', type: 'circle', source: (same as the symbol layer) })`

### Expected Behavior
There are no errors

### Actual Behavior
```
TypeError: Cannot read property 'circle' of undefined
    at Object.drawCircles [as circle] (/Users/anand/c/mapbox/mapbox-gl-js/js/render/draw_circle.js:27:44)
    at Painter.renderLayer (/Users/anand/c/mapbox/mapbox-gl-js/js/render/painter.js:271:25)
    at Painter.renderPass (/Users/anand/c/mapbox/mapbox-gl-js/js/render/painter.js:254:18)
    at Painter.render (/Users/anand/c/mapbox/mapbox-gl-js/js/render/painter.js:213:14)
    at Map._render (/Users/anand/c/mapbox/mapbox-gl-js/js/ui/map.js:1141:22)
    at Immediate.immediate._onImmediate (timers.js:585:18)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)
```

I think the problem is that, since this is happening in a single batch, the it's being treated by the source cache as an update--specifically, the tiles' states are set to `reloading`, so that they are still considered renderable.  In the render pass that happens _after_ the layer's been re-added but _before_ the tile reloading is complete, we end up trying to render them as a circle-layer tiles, but the buffers aren't set up for that yet.

**Comment by anandthakker** [comment]
@jfirebaugh found this while adding a runtime-styling test for setStyle (changing a layer's type) -- do you think this should block https://github.com/mapbox/mapbox-gl-js/pull/3621, or be left as a follow-up? (In the latter case, I could add an `ignore` for js pointing to this issue.)

**Comment by jfirebaugh** [comment]
This sort of situation will be more common with #3621, so let's fix it first.

**Comment by anandthakker** [comment]
:+1: sounds good.
