### ISSUE TITLE
util.js error

### ISSUE THREAD

**Issue by musicformellons** [mapbox/mapbox-gl-js#3724]
When upgrading from 0.26.0 to 0.27.0 I suddenly get following error message. Of course related to deprecation of util.js but how to solve this?:

```
ERROR in ./~/mapbox-gl/js/util/util.js
Module build failed: SyntaxError: Unexpected token (15:35)
    at Parser.pp.raise (/home/usr/pqqf03/node_modules/falafel/node_modules/acorn/dist/acorn.js:1745:13)
    at Parser.pp.unexpected (/home/usr/pqqf03/node_modules/falafel/node_modules/acorn/dist/acorn.js:2264:8)
    at Parser.pp.expect (/home/usr/pqqf03/node_modules/falafel/node_modules/acorn/dist/acorn.js:2258:26)
    at Parser.pp.parseBindingList (/home/usr/pqqf03/node_modules/falafel/node_modules/acorn/dist/acorn.js:1884:40)
    at Parser.pp.parseFunctionParams (/home/usr/pqqf03/node_modules/falafel/node_modules/acorn/dist/acorn.js:2776:22)
    at Parser.pp.parseFunction (/home/usr/pqqf03/node_modules/falafel/node_modules/acorn/dist/acorn.js:2769:8)
    at Parser.pp.parseExprAtom (/home/usr/pqqf03/node_modules/falafel/node_modules/acorn/dist/acorn.js:1129:19)
    at Parser.pp.parseExprSubscripts (/home/usr/pqqf03/node_modules/falafel/node_modules/acorn/dist/acorn.js:1023:19)
    at Parser.pp.parseMaybeUnary (/home/usr/pqqf03/node_modules/falafel/node_modules/acorn/dist/acorn.js:1004:19)
    at Parser.pp.parseExprOps (/home/usr/pqqf03/node_modules/falafel/node_modules/acorn/dist/acorn.js:948:19)
    at Parser.pp.parseMaybeConditional (/home/usr/pqqf03/node_modules/falafel/node_modules/acorn/dist/acorn.js:930:19)
    at Parser.pp.parseMaybeAssign (/home/usr/pqqf03/node_modules/falafel/node_modules/acorn/dist/acorn.js:908:19)
    at Parser.pp.parseMaybeAssign (/home/usr/pqqf03/node_modules/falafel/node_modules/acorn/dist/acorn.js:917:23)
    at Parser.pp.parseExpression (/home/usr/pqqf03/node_modules/falafel/node_modules/acorn/dist/acorn.js:882:19)
    at Parser.pp.parseStatement (/home/usr/pqqf03/node_modules/falafel/node_modules/acorn/dist/acorn.js:2461:23)
    at Parser.pp.parseTopLevel (/home/usr/pqqf03/node_modules/falafel/node_modules/acorn/dist/acorn.js:2379:21)
 @ ./~/mapbox-gl/js/mapbox-gl.js 26:16-38
Child html-webpack-plugin for "index.html":
         Asset     Size  Chunks       Chunk Names
    index.html  20.3 kB       0       
webpack: bundle is now VALID.
```

**Comment by jfirebaugh** [comment]
Please use the dist file for webpack, as documented in the README: https://github.com/mapbox/mapbox-gl-js#using-mapbox-gl-js-with-other-module-systems

**Comment by musicformellons** [comment]
@jfirebaugh Uh, but is this different from version 0.26.0 then? Because everything was working fine...with webpack...

**Comment by jfirebaugh** [comment]
This has been required [since 0.25.0](https://github.com/mapbox/mapbox-gl-js/pull/3235). If using the non-dist file worked in 0.26.0, it was a coincidence.

**Comment by musicformellons** [comment]
Thx. Works now.
