### ISSUE TITLE
Unit tests fail under node 6.10.1

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-js#4471]
Unit tests which pass under 6.10.0 are failing on node 6.10.1, released today. The first failing test is:

```
  1) test/unit/source/canvas_source.test.js CanvasSource rerenders if animated window.useFakeHTMLCanvasGetContext is not a function:
     Error: window.useFakeHTMLCanvasGetContext is not a function
      at createSource (test/unit/source/canvas_source.test.js:11:12)
      at Test.t.test (test/unit/source/canvas_source.test.js:64:24)
      at Test.test (test/unit/source/canvas_source.test.js:63:7)
```

Failed job: https://circleci.com/gh/mapbox/mapbox-gl-js/7292.

#4470 pins to 6.10.0 temporarily so that we can continue working while this is investigated.

**Comment by jfirebaugh** [comment]
Release notes: https://nodejs.org/en/blog/release/v6.10.1/

**Comment by jfirebaugh** [comment]
This was a latent bug exposed by node fixing https://github.com/nodejs/node/issues/6287, which in turn fixes https://github.com/tmpvar/jsdom/issues/1622, which we are implicitly relying on due to the order of actions in [`window.js`]():

1. Delete own properties in `previousWindow` (=== `module.exports`)
2. Extend `module.exports` with contents of fresh jsdom `window`
3. Extend fresh jsdom `window` with our custom properties, e.g. `useFakeHTMLCanvasGetContext`

(2) and (3) should occur in the opposite order. It happened to work in prior version of node because (1) didn't actually delete our custom properties due to the above linked issues.

PR incoming.

**Comment by jfirebaugh** [comment]
...turns out fixing that fixes one issue, but there are others. Stay tuned.
