### ISSUE TITLE
Add updateImage API, or allow addImage to update

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-js#4804]
There's currently no API for updating the image associated with a particular ID. gl-native allows updating an image via `addImage`, but in gl-js that triggers an error.

When implementing this, care should be taken to avoid the gl-js equivalents of https://github.com/mapbox/mapbox-gl-native/issues/6536 and https://github.com/mapbox/mapbox-gl-native/issues/7618.

**Comment by astojilj** [comment]
Reopening this to check/document the issue with render tests:

https://github.com/mapbox/mapbox-gl-js/blob/f2117b4ef501bbab298898e4f6c34083178d519a/test/ignores.json#L12-L13

Fails when enabled and running e.g. `yarn test-render image-update-icon`:

```
Error: Invalid arguments to map.updateImage(). The second argument must be an `HTMLImageElement`, `ImageData`, `ImageBitmap`, or object with `width`, `height`, and `data` properties with the same format as `ImageData`
    at Map.updateImage (/Users/astojilj/mapbox-gl-js/src/ui/map.js:1669:45)
    at applyOperations (/Users/astojilj/mapbox-gl-js/test/suite_implementation.js:181:34)
    at wait (/Users/astojilj/mapbox-gl-js/test/suite_implementation.js:139:25)
    at applyOperations (/Users/astojilj/mapbox-gl-js/test/suite_implementation.js:144:17)
    at Map.<anonymous> (/Users/astojilj/mapbox-gl-js/test/suite_implementation.js:82:9)
    at Map.fire (/Users/astojilj/mapbox-gl-js/src/util/evented.js:125:26)
    at Map._render (/Users/astojilj/mapbox-gl-js/src/ui/map.js:2481:18)
    at Immediate._onImmediate (/Users/astojilj/mapbox-gl-js/src/ui/map.js:2599:22)
    at processImmediate (internal/timers.js:458:21)
    at process.topLevelDomainCallback (domain.js:137:15)
* failed runtime-styling/image-update-icon

```
