### ISSUE TITLE
Error while installing mapbox-gl-js v0.32

### ISSUE THREAD

**Issue by NameFILIP** [mapbox/mapbox-gl-js#4959]
I'm trying to install `mapbox-gl` using npm 5.1.0, but getting an error:

```
➜  test-npm npm i mapbox-gl@0.32 --registry=https://registry.npmjs.org/         
npm http fetch GET 200 https://registry.npmjs.org/mapbox-gl 17ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/bubleify 40ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/csscolorparser 39ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/feature-filter 41ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/pngjs 35ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/shelf-pack 38ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/whoots-js 38ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/request 40ms (from cache)
npm WARN deprecated feature-filter@2.2.0: This package has been merged into the 'mapbox-gl-style-spec' package
npm WARN deprecated shelf-pack@1.1.0: This module is now under the @mapbox namespace: install @mapbox/shelf-pack instead
npm WARN deprecated whoots-js@2.1.0: This module is now under the @mapbox namespace: install @mapbox/whoots-js instead
npm ERR! code 128
npm ERR! Command failed: /usr/local/bin/git checkout d11f6d2775bf5b22534b3b2fb3410755b2473cdf
npm ERR! fatal: reference is not a tree: d11f6d2775bf5b22534b3b2fb3410755b2473cdf
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/fspiridonov/.npm/_logs/2017-07-08T17_45_25_312Z-debug.log
```

In the log file:
```
38 silly pacote git manifest for mapbox-gl-function@github:mapbox/mapbox-gl-function#41c6724e2bbd7bd1eb5991451bbf118b7d02b525 fetched in 494ms
39 silly resolveWithNewModule mapbox-gl-function@1.3.0 checking installable status
40 silly fetchPackageMetaData error for mapbox-gl-style-spec@github:mapbox/mapbox-gl-style-spec#d11f6d2775bf5b22534b3b2fb3410755b2473cdf Command failed: /usr/local/bin/git checkout d11f6d2775bf5b22534b3b2fb3410755b2473cdf
40 silly fetchPackageMetaData fatal: reference is not a tree: d11f6d2775bf5b22534b3b2fb3410755b2473cdf
41 verbose stack Error: Command failed: /usr/local/bin/git checkout d11f6d2775bf5b22534b3b2fb3410755b2473cdf
41 verbose stack fatal: reference is not a tree: d11f6d2775bf5b22534b3b2fb3410755b2473cdf
41 verbose stack
41 verbose stack     at ChildProcess.exithandler (child_process.js:206:12)
41 verbose stack     at emitTwo (events.js:106:13)
41 verbose stack     at ChildProcess.emit (events.js:191:7)
41 verbose stack     at maybeClose (internal/child_process.js:877:16)
41 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
42 verbose cwd /Users/fspiridonov/Dev/test-npm
43 verbose Darwin 16.6.0
44 verbose argv "/Users/fspiridonov/.nvm/versions/node/v6.10.0/bin/node" "/Users/fspiridonov/.nvm/versions/node/v6.10.0/bin/npm" "i" "mapbox-gl@0.32" "--registry=https://registry.npmjs.org/"
45 verbose node v6.10.0
46 verbose npm  v5.1.0
47 error code 128
48 error Command failed: /usr/local/bin/git checkout d11f6d2775bf5b22534b3b2fb3410755b2473cdf
48 error fatal: reference is not a tree: d11f6d2775bf5b22534b3b2fb3410755b2473cdf
49 verbose exit [ 1, true ]
```

I can successfully install 0.33+ versions, looks like something got corrupted with v0.32

**Comment by mourner** [comment]
What happens if you install using Yarn or an older NPM version (such as v3)? In any case, this issue is not actionable because NPM versions can't be unpublished. The only thing left to recommend is to use other versions. You could also try `v0.32.1`.

**Comment by kachkaev** [comment]
Same with v0.32.1 and npm 5.3.0

**Comment by vicapow** [comment]
for others, from best I can tell, this is being caused by https://github.com/yarnpkg/yarn/issues/3407 when using a private registry npmrc that requires authentication

**Comment by NameFILIP** [comment]
Looks like this is fixed in the current nightly build of yarn `yarn version v0.28.0-20170728.2359`
