### ISSUE TITLE
generate-struct-arrays build info seems to be incomplete

### ISSUE THREAD

**Issue by lbud** [mapbox/mapbox-gl-js#5894]
The [build instruction](https://github.com/mapbox/mapbox-gl-js/blob/2124161ebba0c17d764e2e7f78e2d34a283e9bae/src/data/array_types.js#L1) at the top of `array_types.js` seems to be incomplete: just running `node build/generate-struct-arrays.js` with node v6.4.0 throws on the flow annotations:
```
import type {ViewType, StructArrayLayout} from '../src/util/struct_array';
^^^^^^
SyntaxError: Unexpected token import
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:528:28)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```
cc @anandthakker

**Comment by jfirebaugh** [comment]
The build instruction is incorrect; you need to run `node_modules/.bin/flow-node build/generate-struct-arrays.js`. (Or better yet, we should create a `yarn run codegen` task.)
