### ISSUE TITLE
webpack bundle test throw error Blob is not defined

### ISSUE THREAD

**Issue by rbinsztock** [mapbox/mapbox-gl-js#6203]
Hi, 

I am using webpack inside my application since I added it my test suite does not run anymore, I added the same config for mapbox-gl in both files.

```
resolve : {
    alias : {
      ....
      'fusioncharts-xt-enterprise-widgets' : 'fusioncharts-xt-enterprise/js/fusioncharts.widgets',
      'mapbox-gl'                          : 'mapbox-gl/dist/mapbox-gl.js',

      // Specific module for tests
      empty : __dirname + '/test/unit/empty.js'
    },
    modulesDirectories : ['node_modules'],
    root               : [appDir, assetsDir, vendorsDir]
  }
```

I have no problem inside the webpack.config.js but with webpack.config.test.js I got this error showing when I run the test suite : 

```
webpack:///./~/mapbox-gl/dist/mapbox-gl.js?:72
var bundleFn=arguments[3],sources=arguments[4],cache=arguments[5],stringify=JSON.stringify;module.exports=function(r,e){function t(r){d[r]=!0;for(var e in sources[r][1]){var o=sources[r][1][e];d[o]||t(o)}}for(var o,n=Object.keys(cache),a=0,i=n.length;a<i;a++){var s=n[a],u=cache[s].exports;if(u===r||u&&u.default===r){o=s;break}}if(!o){o=Math.floor(Math.pow(16,8)*Math.random()).toString(16);for(var f={},a=0,i=n.length;a<i;a++){var s=n[a];f[s]=s}sources[o]=["function(require,module,exports){"+r+"(self); }",f]}var c=Math.floor(Math.pow(16,8)*Math.random()).toString(16),l={};l[o]=o,sources[c]=["function(require,module,exports){var f = require("+stringify(o)+");(f.default ? f.default : f)(self);}",l];var d={};t(c);var g="("+bundleFn+")({"+Object.keys(d).map(function(r){return stringify(r)+":["+sources[r][0]+","+stringify(sources[r][1])+"]"}).join(",")+"},{},["+stringify(c)+"])",v=window.URL||window.webkitURL||window.mozURL||window.msURL,w=new Blob([g],{type:"text/jav

ReferenceError: Blob is not defined
    at new module.exports (webpack:///./~/mapbox-gl/dist/mapbox-gl.js?:72:952)
    at Object.253.../../source/worker (webpack:///./~/mapbox-gl/dist/mapbox-gl.js?:507:116)
    at s (webpack:///./~/mapbox-gl/dist/mapbox-gl.js?:1:622)
    at eval (webpack:///./~/mapbox-gl/dist/mapbox-gl.js?:1:673)
    at Object.279.../ (webpack:///./~/mapbox-gl/dist/mapbox-gl.js?:559:28)
    at s (webpack:///./~/mapbox-gl/dist/mapbox-gl.js?:1:622)
    at eval (webpack:///./~/mapbox-gl/dist/mapbox-gl.js?:1:673)
    at Object.262../worker_pool (webpack:///./~/mapbox-gl/dist/mapbox-gl.js?:525:29)
    at s (webpack:///./~/mapbox-gl/dist/mapbox-gl.js?:1:622)
    at eval (webpack:///./~/mapbox-gl/dist/mapbox-gl.js?:1:673)
    at Object.190.../render/glyph_manager (webpack:///./~/mapbox-gl/dist/mapbox-gl.js?:381:809)
    at s (webpack:///./~/mapbox-gl/dist/mapbox-gl.js?:1:622)
    at eval (webpack:///./~/mapbox-gl/dist/mapbox-gl.js?:1:673)
    at Object.247.../geo/lng_lat (webpack:///./~/mapbox-gl/dist/mapbox-gl.js?:495:338)
    at s (webpack:///./~/mapbox-gl/dist/mapbox-gl.js?:1:622)
    at eval (webpack:///./~/mapbox-gl/dist/mapbox-gl.js?:1:673)
    at Object.73.../package.json (webpack:///./~/mapbox-gl/dist/mapbox-gl.js?:146:148)
    at s (webpack:///./~/mapbox-gl/dist/mapbox-gl.js?:1:622)
    at e (webpack:///./~/mapbox-gl/dist/mapbox-gl.js?:1:793)
    at eval (webpack:///./~/mapbox-gl/dist/mapbox-gl.js?:1:811)
    at a (webpack:///./~/mapbox-gl/dist/mapbox-gl.js?:1:88)
    at eval (webpack:///./~/mapbox-gl/dist/mapbox-gl.js?:1:324)
    at Object.<anonymous> (/Users/rbinsztock/seloger/bob/client/test/build/test_bundle.js:73:15045)
    at __webpack_require__ (/Users/rbinsztock/seloger/bob/client/test/build/test_bundle.js:1:291)
    at eval (webpack:///./app/bob/dashboard/shared/ui/mapBox/mapBox.controller.js?:8:17)
    at Object.<anonymous> (/Users/rbinsztock/seloger/bob/client/test/build/test_bundle.js:73:10494)
    at __webpack_require__ (/Users/rbinsztock/seloger/bob/client/test/build/test_bundle.js:1:291)
    at eval (webpack:///./app/bob/dashboard/shared/ui/mapBox/mapBox.component.js?:11:15)
    at Object.<anonymous> (/Users/rbinsztock/seloger/bob/client/test/build/test_bundle.js:73:9230)
    at __webpack_require__ (/Users/rbinsztock/seloger/bob/client/test/build/test_bundle.js:1:291)
    at eval (webpack:///./app/bob/dashboard/shared/ui/mapBox/mapBox.module.js?:11:15)
    at Object.<anonymous> (/Users/rbinsztock/seloger/bob/client/test/build/test_bundle.js:73:8441)
    at __webpack_require__ (/Users/rbinsztock/seloger/bob/client/test/build/test_bundle.js:1:291)
    at eval (webpack:///./app/bob/dashboard/agency/agency.module.js?:55:15)
    at Object.<anonymous> (/Users/rbinsztock/seloger/bob/client/test/build/test_bundle.js:70:16938)
    at __webpack_require__ (/Users/rbinsztock/seloger/bob/client/test/build/test_bundle.js:1:291)
    at eval (webpack:///./app/bob/dashboard/ads/ads.module.js?:363:385)
    at Object.<anonymous> (/Users/rbinsztock/seloger/bob/client/test/build/test_bundle.js:14:48)
    at __webpack_require__ (/Users/rbinsztock/seloger/bob/client/test/build/test_bundle.js:1:291)
    at eval (webpack:///./app/bob/dashboard/ads/duplicateList/adDuplicate.service.spec.js?:3:60)
    at Object.<anonymous> (/Users/rbinsztock/seloger/bob/client/test/build/test_bundle.js:13:25967)
    at __webpack_require__ (/Users/rbinsztock/seloger/bob/client/test/build/test_bundle.js:1:291)
    at webpackContext (webpack:///./app/bob_\.spec\.js?:458:9)
    at Array.forEach (native)
    at eval (webpack:///./test/unit/test.entry.js?:12:20)
    at Object.<anonymous> (/Users/rbinsztock/seloger/bob/client/test/build/test_bundle.js:1:959)
    at __webpack_require__ (/Users/rbinsztock/seloger/bob/client/test/build/test_bundle.js:1:291)
    at /Users/rbinsztock/seloger/bob/client/test/build/test_bundle.js:1:889
    at Object.<anonymous> (/Users/rbinsztock/seloger/bob/client/test/build/test_bundle.js:1:912)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at /Users/rbinsztock/seloger/bob/client/node_modules/mocha/lib/mocha.js:220:27
    at Array.forEach (native)
    at Mocha.loadFiles (/Users/rbinsztock/seloger/bob/client/node_modules/mocha/lib/mocha.js:217:14)
    at Mocha.run (/Users/rbinsztock/seloger/bob/client/node_modules/mocha/lib/mocha.js:469:10)
    at Object.<anonymous> (/Users/rbinsztock/seloger/bob/client/node_modules/mocha/bin/_mocha:404:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

I tried to add `noParse : /(mapbox-gl)\.js$/`, but nothing prevent this error to show up, I can mock mapbox-gl and return an empty function but I prefer a true solution.

To prevent the test suite to fail I have added this my webpack.config.test.js

`new webpack.NormalModuleReplacementPlugin(/mapbox-gl/, 'empty')`

Thank you

**Comment by jfirebaugh** [comment]
Yeah, you should mock mapbox-gl; it isn't intended for use in a node environment. https://github.com/mapbox/mapbox-gl-js-mock may help.
