### ISSUE TITLE
Errors in render test related to Worker.enforceCacheSizeLimit

### ISSUE THREAD

**Issue by asheemmamoowala** [mapbox/mapbox-gl-js#8406]
Multiple render tests are throwing errors from `Worker.enforceCacheSizeLimit`

See: https://circleci.com/gh/mapbox/mapbox-gl-js/45149?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

```
TypeError: Cannot read property 'open' of undefined
    at enforceCacheSizeLimit (/root/mapbox-gl-js/src/util/tile_request_cache.js:104:19)
    at Worker.enforceCacheSizeLimit (/root/mapbox-gl-js/src/source/worker.js:201:9)
    at Actor.receive (/root/mapbox-gl-js/src/util/actor.js:101:54)
    at Immediate.setImmediate (/root/mapbox-gl-js/src/util/web_worker.js:60:21)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
```

cc @ansis

**Comment by asheemmamoowala** [comment]
This hasnt been seen in many months. Closing as not reproducible
