### ISSUE TITLE
Invalid LngLat object: (NaN, NaN) in mapbox-gl v1.5.1 and v1.9.0

### ISSUE THREAD

**Issue by mciastek** [mapbox/mapbox-gl-js#9488]
**mapbox-gl-js version**: 1.5.1, 1.9.0

**browser**: Chrome, Firefox, Safari

### Steps to Trigger Behavior

Probably during interacting with map using mouse. I received a lot of such errors from different browser clients in Sentry. Here's a stack trace:

```
Error: Invalid LngLat object: (NaN, NaN)
  at new Nu(../src/geo/lng_lat.js:30:19)
  at toLngLat(../src/geo/mercator_coordinate.js:117:16)
  at coordinateLocation(../src/geo/transform.js:345:22)
  at pointLocation(../src/geo/transform.js:326:21)
  at unproject(../src/ui/map.js:714:31)
  at new o(../src/ui/events.js:80:28)
  at apply(../src/ui/bind_handlers.js:106:18)
  at HTMLDivElement.d(raven.js:445:21) --> this one can be ignored, because it's Sentry
```

What's interesting here, that this error originates from:

<img width="668" alt="Screenshot 2020-04-01 at 17 16 37" src="https://user-images.githubusercontent.com/3169629/78154458-94b57080-743c-11ea-8052-c1fab326545a.png">

As we're using Maptiler, I'm not totally sure if we can update mapbox to the latest one.

EDIT:

The same bug appears after I updated version to 1.9.0.

**Comment by asheemmamoowala** [comment]
Thank you for your opening this ticket. To help the maintainers and community understand and address the problem accurately can you please provide a minimal, complete, verifiable demonstration of the issue. We recommend using https://jsbin.com.

**Comment by mciastek** [comment]
After some investigation, it appears that we've been crawled by Facebook bot. Their bot probably crawls a page and fires events without `Event` object or `clientX` and `clientY` properties. Considering a list of IPs that matches Facebook bot's IPs, I think that was this bot. I think that normal browser would never fire a `mouseout` event without mentioned properties.

We can close this issue for now. I'll be monitoring this error and reopen this issue if the event will appear again.
